channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=23.2.1
- pip:
  - mlflow==2.7.0
  - cloudpickle==2.2.1
  - feature-engine==1.6.2
  - numpy==1.26.0
  - packaging==23.1
  - pandas==2.1.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.5.2
  - scipy==1.11.3
name: mlflow-env
